version: "3"

services:
    go:
        build:
            context: ./dockerFile/go
            args:
                - GO_VERSION=${GO_VERSION}
        restart: always
        container_name: go
        stdin_open: true
        tty: true
        volumes:
          - ${SITE_PATH}:/go/project
        ports:
            - "8080:8080"


